# Uncomment this line to define a global platform for your project
# platform :ios, '8.0'
# Uncomment this line if you're using Swift
# use_frameworks!

target 'testReactiveCocoa' do
pod ‘ReactiveCocoa’,’~>4.1’
use_frameworks!
end

target 'testReactiveCocoaTests' do

end

target 'testReactiveCocoaUITests' do

end



